
spring:
  datasource:
    username: root
    password: theday1012
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.bei.loginserver.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml